### ISSUE TITLE
Dodał bym info o fajnych programach

### ISSUE THREAD

**Issue by welon68** [qarmin/GNU-Linux-Podstawy#2]
takich jak
mpv
Flowblade
Qnapi
itp

**Comment by qarmin** [comment]
To repozytorium zawiera tylko podstawowe informacje o Linuxie.
W tekście istnieje odniesienie do innego mojego repozytorium - https://github.com/qarmin/Rewelacyjne-OpenSource - zawierającego masę darmowego oprogramowania oprogramowania
